### ISSUE TITLE
Bump the version number please

### ISSUE THREAD

**Issue by boncey** [augustl/ruby-prowl#9]
The version number wasn't changed after the last commit (a [merged pull request](https://github.com/augustl/ruby-prowl/commit/e8527476cace08db76d9c83bc45e409844771ccf)).
That commit updated the API URL but as the version number wasn't changed bundle won't see the changes and pull down the latest version.

My rails app is set to use `0.1.3` but still has the old version - which tries to use the old endpoint.

```
  API_URL = "https://prowl.weks.net:443/publicapi"
```

That URL has recently stopped working which is causing my application to fail.

As I understand it the only other workaround for me is to fork the repo, bump the version number myself then tell Bundler to use that version.
Or you could bump the version number, it should be a really quick fix and would really help me out of a tight spot.

Thanks in advance, Darren.

**Comment by augustl** [comment]
Hey! Just realized I've disabled github notification e-mails so projects like this one that I don't actively check on has been completely dark..

Do you know what the new URL is?

**Comment by boncey** [comment]
Your code has the correct URL, it just needs a new version number so that anyone who had downloaded the old version (like me) can pick up the new one.

**Comment by augustl** [comment]
Ah, thanks! This is embarassing.. But good to know that someone still finds my code useful :)

I'll do a release right away.

**Comment by boncey** [comment]
Brilliant, thanks for that.

**Comment by augustl** [comment]
0.1.4 is out on rubygems.org, thanks for the heads up!
